server:
  tomcat:
    threads:
      max: 20

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-228-32-29.eu-west-1.compute.amazonaws.com:5432/d5rmr834rpsivd
    username: abprrczzhxgnoq
    password: 8de426755ddc4432eb6e88ad4b3bee38a7a44981793cca10762379417ce926dc
  jpa:
    show-sql: false

security:
  invitation-link:
    expiration-sec: 864000
  jwt:
    secret: 5dd913ac-5fdf-48bc-bbeb-38631d86cc16
    expiration-sec: 300
    refresh-token-expiration-sec: 259200

logging:
  level:
    ru.sourcemap.template: DEBUG